blueprint:
  name: Alarme para Sirene Avançado
  description: >-
    Dispara uma sirene quando um sensor de porta/janela muda para um estado específico.
    
    Recursos disponíveis - Ativação/desativação do som - Nível de volume configurável - Melodia/tom personalizável - Duração do alarme (0 para indefinido) - Modo de repetição - Notificação opcional - Tempo de espera antes de reativar
  domain: automation

input:
  # ========== GATILHO ==========
  trigger_sensor:
    name: Sensor de Gatilho
    description: O sensor que irá disparar o alarme (porta, janela, movimento, etc)
    selector:
      entity:
        domain: 
          - binary_sensor
          - sensor

  trigger_state:
    name: Estado para Disparar
    description: O estado do sensor que deve acionar o alarme
    default: "on"
    selector:
      select:
        options:
          - label: "Aberto / Detectando (on)"
            value: "on"
          - label: "Fechado / Limpo (off)"
            value: "off"

  # ========== DISPOSITIVO ==========
  alarm_device:
    name: Dispositivo de Alarme
    description: A entidade 'siren' (NAS-AB02B2 ou similar)
    selector:
      entity:
        domain: siren

  # ========== CONFIGURAÇÕES DE SOM ==========
  enable_sound:
    name: Ativar Som
    description: Se marcado, o alarme emitirá som
    default: true
    selector:
      boolean:

  volume_level:
    name: Nível de Volume
    description: Volume do alarme (0% = mudo, 100% = máximo)
    default: 100
    selector:
      number:
        min: 0
        max: 100
        step: 5
        unit_of_measurement: "%"
        mode: slider

  melody_tone:
    name: Melodia / Tom
    description: >-
      Tom da sirene. Valores comuns são alarm, doorbell, chime, siren.
      Verifique em Ferramentas do Desenvolvedor > Estados os valores suportados.
    default: "alarm"
    selector:
      select:
        options:
          - "alarm"
          - "doorbell"
          - "chime"
          - "siren"
          - "emergency"
        custom_value: true

  duration_seconds:
    name: Duração do Alarme
    description: Tempo que o alarme tocará (0 = indefinido, até parar manualmente)
    default: 60
    selector:
      number:
        min: 0
        max: 600
        step: 5
        unit_of_measurement: "segundos"
        mode: box

  # ========== OPÇÕES AVANÇADAS ==========
  repeat_alarm:
    name: Repetir Alarme
    description: Repetir o alarme múltiplas vezes (útil para durações curtas)
    default: 1
    selector:
      number:
        min: 1
        max: 10
        step: 1
        mode: box

  delay_between_repeats:
    name: Pausa entre Repetições
    description: Tempo de espera entre cada repetição do alarme
    default: 2
    selector:
      number:
        min: 0
        max: 60
        step: 1
        unit_of_measurement: "segundos"
        mode: box

  cooldown_period:
    name: Período de Espera (Cooldown)
    description: Tempo mínimo entre acionamentos do alarme (evita disparos múltiplos)
    default: 30
    selector:
      number:
        min: 0
        max: 300
        step: 5
        unit_of_measurement: "segundos"
        mode: box

  # ========== NOTIFICAÇÕES ==========
  send_notification:
    name: Enviar Notificação
    description: Enviar notificação quando o alarme disparar
    default: false
    selector:
      boolean:

  notification_service:
    name: Serviço de Notificação
    description: Selecione o serviço para enviar notificação (exemplo - notify.mobile_app_seu_telefone)
    default: []
    selector:
      target:
        entity:
          - domain: notify

  notification_title:
    name: Título da Notificação
    description: Título da mensagem de notificação
    default: "Alarme Disparado"
    selector:
      text:

  notification_message:
    name: Mensagem da Notificação
    description: Corpo da notificação. Use variável trigger_name para o nome do sensor
    default: "O sensor foi ativado"
    selector:
      text:
        multiline: true

# ========== VARIÁVEIS ==========
variables:
  sensor_entity: !input trigger_sensor
  alarm_entity: !input alarm_device
  sound_enabled: !input enable_sound
  volume: !input volume_level
  tone: !input melody_tone
  duration: !input duration_seconds
  repeats: !input repeat_alarm
  repeat_delay: !input delay_between_repeats
  cooldown: !input cooldown_period
  notify_enabled: !input send_notification
  notify_target: !input notification_service
  notify_title: !input notification_title
  notify_message: !input notification_message
  trigger_name: "{{ state_attr(sensor_entity, 'friendly_name') | default(sensor_entity) }}"

# ========== GATILHO ==========
trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: !input trigger_state
    for:
      seconds: 2

# ========== CONDIÇÕES ==========
condition:
  - condition: template
    value_template: >-
      {% set last_triggered = state_attr(this.entity_id, 'last_triggered') %}
      {% if last_triggered == none %}
        true
      {% else %}
        {{ (now() - last_triggered).total_seconds() > cooldown }}
      {% endif %}

# ========== AÇÃO ==========
action:
  # 1. Envia notificação (se habilitada)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notify_enabled }}"
          - condition: template
            value_template: "{{ notify_target is defined and notify_target != [] }}"
        sequence:
          - service: notify.send_message
            target: !input notification_service
            data:
              title: "{{ notify_title }}"
              message: "{{ notify_message.replace('trigger_name', trigger_name) }}"

  # 2. Ativa o alarme (se o som estiver habilitado)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ sound_enabled }}"
        sequence:
          - repeat:
              count: "{{ repeats }}"
              sequence:
                - service: siren.turn_on
                  target:
                    entity_id: "{{ alarm_entity }}"
                  data:
                    volume_level: "{{ volume / 100 }}"
                    tone: "{{ tone }}"
                    duration: >-
                      {% if duration > 0 %}
                        {{ duration }}
                      {% endif %}

                - condition: template
                  value_template: "{{ repeat.index < repeats }}"
                
                - delay:
                    seconds: "{{ duration + repeat_delay if duration > 0 else repeat_delay }}"

mode: single
max_exceeded: silent