blueprint:
  name: Alerta Inteligente de Janela Aberta na Chuva (2025 Corrigido)
  description: >
    Sistema avançado de notificação que alerta quando começa a chover e janelas/portas
    estão abertas. Inclui previsão de chuva, múltiplos níveis de alerta, ações automáticas,
    período de silêncio e notificações persistentes com ações rápidas.
  domain: automation
  
  author: Evolução 2025 (Corrigido por Gemini)
  homeassistant:
    min_version: 2024.1.0

  input:
    # ============================================
    # SEÇÃO: SENSORES E MONITORAMENTO
    # ============================================
    rain_sensor:
      name: Sensor de Chuva Principal
      description: Sensor que detecta quando está chovendo ativamente.
      selector:
        entity:
          domain: binary_sensor
          multiple: false

    rain_forecast:
      name: Sensor de Previsão de Chuva (Opcional)
      description: >
        Sensor que indica chuva (ex: weather entity ou sensor customizado).
        NOTA: Isto dispara quando o estado ATUAL é 'rainy', não como previsão futura.
      default: []
      selector:
        entity:
          domain: 
            - weather
            - binary_sensor
          multiple: false

    window_sensors:
      name: Sensores de Janela/Porta
      description: Todas as janelas ou portas que devem ser monitoradas.
      selector:
        entity:
          domain: binary_sensor
          device_class: 
            - door
            - window
            - opening
          multiple: true

    priority_windows:
      name: Janelas Prioritárias (Opcional)
      description: >
        Janelas críticas que geram alerta imediato e mais enfático
        (ex: janelas que dão para áreas sensíveis).
      default: []
      selector:
        entity:
          domain: binary_sensor
          device_class: 
            - door
            - window
            - opening
          multiple: true

    # ============================================
    # SEÇÃO: NOTIFICAÇÕES
    # ============================================
    notify_service:
      name: Serviço de Notificação
      description: >
        Serviço para enviar notificações (ex: notify.mobile_app_iphone,
        notify.all_devices, notify.familia).
      selector:
        text:

    critical_notification:
      name: Usar Notificação Crítica
      description: >
        Ativa notificação crítica (ignora modo silencioso no celular) 
        para janelas prioritárias.
      default: false
      selector:
        boolean:

    notification_sound:
      name: Som da Notificação (Opcional)
      description: Nome do arquivo de som personalizado.
      default: ''
      selector:
        text:

    # ============================================
    # SEÇÃO: MENSAGENS PERSONALIZADAS
    # ============================================
    message_title_active:
      name: Título - Chuva Ativa
      description: Título quando a chuva já começou.
      default: "ALERTA: Chuva e Janelas Abertas!"
      selector:
        text:

    message_title_forecast:
      name: Título - Previsão de Chuva
      description: Título para alerta (baseado no estado atual da previsão).
      default: " AVISO: Chuva Prevista e Janelas Abertas"
      selector:
        text:

    message_body:
      name: Corpo da Mensagem
      description: >
        Texto da notificação. Variáveis disponíveis:
        {janelas_abertas}, {total}, {prioritarias}, {tempo}
      default: >
        Está chovendo agora! {total} abertura(s) detectada(s): {janelas_abertas}.
        {prioritarias}
        Feche-as imediatamente para evitar danos.
      selector:
        text:
          multiline: true

    # ============================================
    # SEÇÃO: AÇÕES AUTOMÁTICAS
    # ============================================
    auto_close_covers:
      name: Fechar Coberturas Automaticamente
      description: >
        Fecha automaticamente persianas/cortinas elétricas quando detectar chuva.
      default: []
      selector:
        entity:
          domain: cover
          multiple: true

    turn_off_devices:
      name: Desligar Dispositivos (Opcional)
      description: >
        Dispositivos para desligar automaticamente quando chover
        (ex: ventiladores perto de janelas).
      default: []
      selector:
        entity:
          domain: 
            - switch
            - fan
          multiple: true

    activate_scene:
      name: Cena para Ativar (Opcional)
      description: Cena do Home Assistant para executar quando chover.
      default: ''
      selector:
        entity:
          domain: scene
          multiple: false

    # ============================================
    # SEÇÃO: COMPORTAMENTO E CONTROLE
    # ============================================
    forecast_advance_time:
      name: Tempo de Antecedência (NÃO FUNCIONAL)
      description: >
        AVISO: Este campo não é usado pela automação!
        A lógica de alerta preventivo não está implementada.
      default: 30
      selector:
        number:
          min: 5
          max: 120
          step: 5
          unit_of_measurement: "minutos"

    repeat_notification:
      name: Repetir Notificação
      description: Enviar notificações repetidas enquanto janelas estiverem abertas.
      default: true
      selector:
        boolean:

    repeat_interval:
      name: Intervalo de Repetição
      description: Tempo entre notificações repetidas.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: "minutos"

    max_repeats:
      name: Máximo de Repetições
      description: Número máximo de notificações repetidas (0 = ilimitado).
      default: 5
      selector:
        number:
          min: 0
          max: 20
          step: 1

    quiet_hours_enabled:
      name: Ativar Período de Silêncio
      description: Não enviar notificações durante horários específicos.
      default: false
      selector:
        boolean:

    quiet_start_time:
      name: Início do Período de Silêncio
      # CORREÇÃO: Aspas adicionadas
      description: "Hora de início (exemplo 22:00)."
      default: "22:00:00"
      selector:
        time:

    quiet_end_time:
      name: Fim do Período de Silêncio
      # CORREÇÃO: Aspas adicionadas
      description: "Hora de término (exemplo 07:00)."
      default: "07:00:00"
      selector:
        time:

    override_quiet_for_priority:
      name: Ignorar Silêncio para Janelas Prioritárias
      description: Enviar notificações de janelas prioritárias mesmo no período de silêncio.
      default: true
      selector:
        boolean:

    # ============================================
    # SEÇÃO: RECURSOS AVANÇADOS
    # ============================================
    enable_actionable_notifications:
      name: Ações Rápidas na Notificação
      description: >
        Adiciona botões na notificação (apenas mobile_app):
        "Fechar Tudo", "Lembrar em 5min", "Ignorar".
      default: true
      selector:
        boolean:

    enable_tts_announcement:
      name: Anúncio por Voz (TTS)
      description: Fazer anúncio de voz em alto-falantes inteligentes.
      default: false
      selector:
        boolean:

    tts_service:
      name:  Serviço TTS
      # CORREÇÃO: Aspas adicionadas
      description: "Serviço de text-to-speech (ex: tts.google_say)."
      default: ''
      selector:
        text:

    tts_target:
      name:  Dispositivos para TTS
      description: Media players para anúncio de voz.
      default: []
      selector:
        entity:
          domain: media_player
          multiple: true

    log_to_logbook:
      name:  Registrar no Histórico
      description: Criar entrada no logbook do Home Assistant.
      default: true
      selector:
        boolean:

mode: restart
max_exceeded: silent

# ===================================================================
# VARIÁVEIS PRINCIPAIS
# ===================================================================
variables:
  # Listas de sensores
  lista_sensores_janelas: !input window_sensors
  lista_janelas_prioritarias: !input priority_windows
  lista_coberturas: !input auto_close_covers
  lista_dispositivos: !input turn_off_devices
  
  # Configurações
  usar_critico: !input critical_notification
  repeticoes_ativas: !input repeat_notification
  intervalo_repeticao: !input repeat_interval
  max_repeticoes: !input max_repeats
  silencio_ativo: !input quiet_hours_enabled
  silencio_inicio: !input quiet_start_time
  silencio_fim: !input quiet_end_time
  ignorar_silencio_prioritarias: !input override_quiet_for_priority
  acoes_ativas: !input enable_actionable_notifications
  tts_ativo: !input enable_tts_announcement
  log_ativo: !input log_to_logbook

  # Variáveis para usar !inputs dentro de templates Jinja
  rain_sensor_entity: !input rain_sensor
  title_forecast: !input message_title_forecast
  title_active: !input message_title_active
  message_content: !input message_body
  sound_file: !input notification_sound
  tts_service_name: !input tts_service
  
  # Cálculo de janelas abertas
  janelas_abertas_lista: >
    {{ expand(lista_sensores_janelas) 
       | selectattr('state', 'eq', 'on')
       | map(attribute='name') 
       | list }}
       
  janelas_prioritarias_abertas: >
    {{ expand(lista_janelas_prioritarias) 
       | selectattr('state', 'eq', 'on')
       | map(attribute='name') 
       | list }}
       
  total_abertas: "{{ janelas_abertas_lista | count }}"
  
  tem_prioritarias: "{{ janelas_prioritarias_abertas | count > 0 }}"
  
  janelas_texto: "{{ janelas_abertas_lista | join(', ') }}"
  
  prioritarias_texto: >
    {% if tem_prioritarias %}
     ATENÇÃO ESPECIAL: {{ janelas_prioritarias_abertas | join(', ') }}
    {% else %}
    {% endif %}
  
  # Lógica de período de silêncio
  em_periodo_silencio: >
    {% if silencio_ativo %}
      {% set start = (silencio_inicio | as_time) %}
      {% set end = (silencio_fim | as_time) %}
      {% set now_time = now().time() %}
      {% if start <= end %}
        {# Período que NÃO cruza a meia-noite (ex: 09:00 às 17:00) #}
        {{ start <= now_time <= end }}
      {% else %}
        {# Período que cruza a meia-noite (ex: 22:00 às 07:00) #}
        {{ now_time >= start or now_time <= end }}
      {% endif %}
    {% else %}
      false
    {% endif %}
    
  deve_notificar: >
    {{ not em_periodo_silencio or 
       (ignorar_silencio_prioritarias and tem_prioritarias) }}

# ===================================================================
# GATILHOS (TRIGGERS)
# ===================================================================
trigger:
  # Trigger 1: Chuva ativa detectada
  - platform: state
    id: chuva_ativa
    entity_id: !input rain_sensor
    to: 'on'
  
  # Trigger 2: Previsão de chuva (se configurado)
  - platform: state
    id: chuva_prevista
    entity_id: !input rain_forecast
    to: 
      - 'rainy'
      - 'pouring'
      - 'on'

  # Trigger 3: Janela aberta durante chuva
  - platform: state
    id: janela_aberta
    entity_id: !input window_sensors
    to: 'on'

# ===================================================================
# CONDIÇÕES (CONDITIONS)
# ===================================================================
condition:
  # Só aciona se houver janelas abertas
  - condition: template
    value_template: "{{ total_abertas | int > 0 }}"
  
  # Verificar se deve notificar (período de silêncio)
  - condition: template
    value_template: "{{ deve_notificar }}"
  
  # Forma mais robusta de verificar a chuva.
  - condition: or
    conditions:
      - condition: state
        entity_id: !input rain_sensor
        state: 'on'
      - condition: state
        entity_id: !input rain_forecast
        state: 
          - 'rainy'
          - 'pouring'
          - 'on'

# ===================================================================
# AÇÕES (ACTION)
# ===================================================================
action:
  # ============================================
  # PASSO 1: AÇÕES AUTOMÁTICAS
  # ============================================
  
  # Fechar coberturas automaticamente
  - if:
      - condition: template
        value_template: "{{ lista_coberturas | count > 0 }}"
    then:
      - service: cover.close_cover
        target:
          entity_id: !input auto_close_covers
      
      - if:
          - condition: template
            value_template: "{{ log_ativo }}"
        then:
          - service: logbook.log
            data:
              name: " Automação Chuva"
              message: "Coberturas fechadas automaticamente: {{ lista_coberturas | join(', ') }}"

  # Desligar dispositivos
  - if:
      - condition: template
        value_template: "{{ lista_dispositivos | count > 0 }}"
    then:
      - service: homeassistant.turn_off
        target:
          entity_id: !input turn_off_devices

  # Ativar cena
  - if:
      - condition: template
        value_template: "{{ !input activate_scene != '' }}"
    then:
      - service: scene.turn_on
        target:
          entity_id: !input activate_scene

  # ============================================
  # PASSO 2: NOTIFICAÇÕES
  # ============================================
  
  # Preparar dados da notificação
  - variables:
      titulo_notificacao: >
        {% if trigger.id == 'chuva_prevista' %}
          {{ title_forecast }}
        {% else %}
          {{ title_active }}
        {% endif %}
      
      corpo_notificacao: >
        {{ message_content 
           | replace('{janelas_abertas}', janelas_texto)
           | replace('{total}', total_abertas | string)
           | replace('{prioritarias}', prioritarias_texto)
           | replace('{tempo}', now().strftime('%H:%M')) }}
      
      dados_notificacao: >
        {% set data = namespace(dict={}) %}
        {% if usar_critico and tem_prioritarias %}
          {% set data.dict = dict(data.dict, **{'push': {'sound': {'name': 'default', 'critical': 1, 'volume': 1.0}}}) %}
        {% elif sound_file != '' %}
          {% set data.dict = dict(data.dict, **{'push': {'sound': sound_file }}) %}
        {% endif %}
        {% if acoes_ativas %}
          {% set data.dict = dict(data.dict, **{'actions': [
            {'action': 'CLOSE_ALL', 'title': 'Fechar Tudo'},
            {'action': 'SNOOZE_5MIN', 'title': 'Lembrar em 5min'},
            {'action': 'DISMISS', 'title': 'Ignorar'}
          ]}) %}
        {% endif %}
        {{ data.dict }}

  # Enviar notificação principal
  - service: !input notify_service
    data:
      title: "{{ titulo_notificacao }}"
      message: "{{ corpo_notificacao }}"
      data: **: "{{ dados_notificacao }}"

  # ============================================
  # PASSO 3: TTS (se ativado)
  # ============================================
  
  - if:
      - condition: template
        value_template: "{{ tts_ativo and tts_service_name != '' }}"
    then:
      - service: !input tts_service
        target:
          entity_id: !input tts_target
        data:
          message: >
            Atenção! Está chovendo e {{ total_abertas }} janela(s) está(ão) aberta(s).
            Por favor, feche: {{ janelas_texto }}.

  # ============================================
  # PASSO 4: LOGBOOK
  # ============================================
  
  - if:
      - condition: template
        value_template: "{{ log_ativo }}"
    then:
      - service: logbook.log
        data:
          name: " Alerta de Chuva"
          message: >
            Detectada chuva com {{ total_abertas }} abertura(s): {{ janelas_texto }}.
            {% if tem_prioritarias %}Janelas prioritárias abertas!{% endif %}
          entity_id: !input rain_sensor

  # ============================================
  # PASSO 5: REPETIÇÃO (se configurado)
  # ============================================
  
  - if:
      - condition: template
        value_template: "{{ repeticoes_ativas }}"
    then:
      - repeat:
          while:
            - condition: template
              value_template: >
                {{ states(rain_sensor_entity) == 'on' and
                   expand(lista_sensores_janelas) | selectattr('state', 'eq', 'on') | list | count > 0 and
                   (max_repeticoes == 0 or repeat.index <= max_repeticoes) }}
          sequence:
            - delay:
                minutes: "{{ intervalo_repeticao }}"
            
            - variables:
                janelas_ainda_abertas: >
                  {{ expand(lista_sensores_janelas) 
                     | selectattr('state', 'eq', 'on')
                     | map(attribute='name') 
                     | list | join(', ') }}
            
            - service: !input notify_service
              data:
                title: " Lembrete: Janelas ainda abertas"
                message: >
                  A chuva continua! Ainda há {{ expand(lista_sensores_janelas) | selectattr('state', 'eq', 'on') | list | count }}
                  abertura(s): {{ janelas_ainda_abertas }}. (Lembrete {{ repeat.index }})
