blueprint:
  name: Controle de Interruptor por Nível de Umidade (Histerese)
  description: >-
    Liga um dispositivo (interruptor, ventilador, etc.) quando um sensor de 
    umidade atinge um limite superior e o desliga quando atinge um 
    limite inferior. Isso evita que o dispositivo ligue e desligue 
    rapidamente (histerese).
  domain: automation
  input:
    humidity_sensor:
      name: Sensor de Umidade
      description: O sensor que irá monitorar a umidade.
      selector:
        entity:
          domain: sensor
          device_class: humidity
    target_device:
      name: Dispositivo a Controlar
      description: O interruptor, ventilador ou luz que será ligado/desligado.
      selector:
        entity:
          domain:
            - switch
            - fan
            - light
            - input_boolean
    humidity_high_threshold:
      name: 'Limite Superior para LIGAR'
      description: A umidade (%) acima da qual o dispositivo deve LIGAR.
      default: 70
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
          mode: slider
          step: 1
    humidity_low_threshold:
      name: 'Limite Inferior para DESLIGAR'
      description: >-
        A umidade (%) abaixo da qual o dispositivo deve DESLIGAR. 
        (Deve ser menor que o limite de LIGAR).
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
          mode: slider
          step: 1
    enable_min_duration:
      name: 'Ativar Duração Mínima'
      description: Ativar tempo mínimo antes de acionar (previne flutuações).
      default: false
      selector:
        boolean:
    min_duration:
      name: 'Duração Mínima'
      description: >-
        Tempo mínimo que a umidade deve permanecer acima/abaixo do limite 
        antes de acionar. Só funciona se "Ativar Duração Mínima" estiver ligado.
      default: 30
      selector:
        number:
          min: 5
          max: 300
          unit_of_measurement: 'segundos'
          mode: slider
          step: 5

mode: restart
max_exceeded: silent

trigger:
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: !input humidity_high_threshold
    id: 'turn_on'
  - platform: numeric_state
    entity_id: !input humidity_sensor
    below: !input humidity_low_threshold
    id: 'turn_off'

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: 'turn_on'
        sequence:
          - if:
              - condition: template
                value_template: "{{ enable_min_duration }}"
            then:
              - wait_template: >-
                  {{ states(humidity_sensor) | float(0) > humidity_high_threshold | float(0) }}
                timeout:
                  seconds: !input min_duration
                continue_on_timeout: false
          - condition: state
            entity_id: !input target_device
            state: 'off'
          - action: homeassistant.turn_on
            target:
              entity_id: !input target_device
      
      - conditions:
          - condition: trigger
            id: 'turn_off'
        sequence:
          - if:
              - condition: template
                value_template: "{{ enable_min_duration }}"
            then:
              - wait_template: >-
                  {{ states(humidity_sensor) | float(0) < humidity_low_threshold | float(0) }}
                timeout:
                  seconds: !input min_duration
                continue_on_timeout: false
          - condition: state
            entity_id: !input target_device
            state: 'on'
          - action: homeassistant.turn_off
            target:
              entity_id: !input target_device

variables:
  humidity_sensor: !input humidity_sensor
  humidity_high_threshold: !input humidity_high_threshold
  humidity_low_threshold: !input humidity_low_threshold
  enable_min_duration: !input enable_min_duration
