blueprint:
  name: Sincronia Total (Multi-Switch + Climate + Luz Opcional)
  description: >
    Sincroniza múltiplos interruptores, um ar condicionado e uma luz auxiliar opcional.
    
    - Mudar QUALQUER interruptor (on/off) muda o estado do AC e de TODOS os outros interruptores.
    - Mudar o AC (pelo app, controle) muda o estado de TODOS os interruptores.
    - Opcionalmente, pode sincronizar uma luz auxiliar (ex: luz do painel) com o estado do AC.
    - Opcionalmente, define modo e temperatura ao ligar.
    
    Otimizado para performance e 100% livre de loops de sincronização.
  domain: automation
  
  input:
    switch_entities:
      name: (Obrigatório) Entidades dos Interruptores
      description: Selecione UM OU MAIS interruptores (switch) que você quer sincronizar.
      selector:
        entity:
          domain: switch
          multiple: true
          
    climate_entity:
      name: (Obrigatório) Entidade do Ar Condicionado
      description: O ar condicionado (climate) que você quer sincronizar.
      selector:
        entity:
          domain: climate

    # --- Nova Seção para Luz Auxiliar ---
    sync_light_toggle:
      name: (Opcional) Sincronizar uma luz auxiliar?
      description: Marque se deseja sincronizar uma luz (ex: painel do AC, luz de status) com o AC.
      selector:
        boolean: {}
      default: false
      
    light_entity:
      name: (Opcional) Entidade da Luz Auxiliar
      description: A entidade (light ou switch) que será sincronizada com o estado do AC.
      selector:
        entity:
          domain:
            - light
            - switch
            
    # --- Seção Opcional Preservada ---
    hvac_mode_input:
      name: (Opcional) Modo do AC ao Ligar
      description: >
        Definir este modo HVAC (ex: 'cool', 'heat') quando o AC LIGAR.
        Se não for definido, o AC ligará no último modo usado ou usará 'climate.turn_on'.
      selector:
        select:
          options:
            - 'cool'
            - 'heat'
            - 'heat_cool'
            - 'auto'
            - 'dry'
            - 'fan_only'
          mode: dropdown
          
    target_temperature_input:
      name: (Opcional) Temperatura Alvo ao Ligar
      description: Definir esta temperatura (em °C ou °F) quando o AC LIGAR.
      selector:
        number:
          min: 16
          max: 30
          step: 0.5
          mode: box

# Define as variáveis com os inputs para facilitar a leitura
variables:
  switches: !input switch_entities
  climate: !input climate_entity
  sync_light: !input sync_light_toggle
  light: !input light_entity
  hvac_mode: !input hvac_mode_input
  target_temp: !input target_temperature_input

# Otimizado para sincronização de estado
mode: restart

# A automação será disparada quando QUALQUER uma das entidades monitoradas mudar
trigger:
  - platform: state
    entity_id: !input switch_entities
  - platform: state
    entity_id: !input climate_entity
    # Ignora mudanças de atributos (temp, etc) se o estado (on/off) for o mesmo
    not_from:
      - "off"
    not_to:
      - "off"

action:
  - choose:
      # --- CASO 1: UM DOS INTERRUPTORES FOI O GATILHO ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id in switches }}"
        sequence:
          # Define o estado alvo (o que o interruptor acabou de se tornar)
          - variables:
              target_state: "{{ trigger.to_state.state }}" # 'on' ou 'off'

          # 1. Sincronizar OS OUTROS interruptores (Lógica Cirúrgica)
          - service: "switch.turn_{{ target_state }}"
            target:
              entity_id: >
                {{ (expand(switches) 
                   | selectattr('entity_id', '!=', trigger.entity_id)
                   | selectattr('state', '!=', target_state) 
                   | map(attribute='entity_id')) | list }}

          # 2. Sincronizar o AR CONDICIONADO
          - choose:
              # --- SUB-CASO 1.1: Interruptor LIGOU ---
              - conditions:
                  - condition: template
                    value_template: "{{ target_state == 'on' and is_state(climate, 'off') }}"
                sequence:
                  # Lógica de "Ligar" com opções
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ hvac_mode is not none }}"
                        sequence:
                          - service: climate.set_hvac_mode
                            target:
                              entity_id: "{{ climate }}"
                            data:
                              hvac_mode: "{{ hvac_mode }}"
                          - if:
                              - condition: template
                                value_template: "{{ target_temp is not none }}"
                            then:
                              - service: climate.set_temperature
                                target:
                                  entity_id: "{{ climate }}"
                                data:
                                  temperature: "{{ target_temp }}"
                      - conditions:
                          - condition: template
                            value_template: "{{ target_temp is not none }}"
                        sequence:
                          - service: climate.turn_on
                            target:
                              entity_id: "{{ climate }}"
                          - service: climate.set_temperature
                            target:
                              entity_id: "{{ climate }}"
                            data:
                              temperature: "{{ target_temp }}"
                    default:
                      - service: climate.turn_on
                        target:
                          entity_id: "{{ climate }}"
              
              # --- SUB-CASO 1.2: Interruptor DESLIGOU ---
              - conditions:
                  - condition: template
                    value_template: "{{ target_state == 'off' and not is_state(climate, 'off') }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: "{{ climate }}"
            default: []
          
          # 3. Sincronizar a LUZ AUXILIAR (se habilitado)
          - if:
              - condition: template
                value_template: "{{ sync_light and light is not none and states(light) != target_state }}"
            then:
              - service: "homeassistant.turn_{{ target_state }}"
                target:
                  entity_id: "{{ light }}"


      # --- CASO 2: O AR CONDICIONADO FOI O GATILHO ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == climate }}"
        sequence:
          # Define o estado alvo (AC 'off' é 'off', qualquer outra coisa é 'on')
          - variables:
              target_state: "{{ 'on' if trigger.to_state.state != 'off' else 'off' }}"

          # 1. Sincronizar TODOS os interruptores (Lógica Cirúrgica)
          - service: "switch.turn_{{ target_state }}"
            target:
              entity_id: >
                {{ (expand(switches) 
                   | selectattr('state', '!=', target_state) 
                   | map(attribute='entity_id')) | list }}
          
          # 2. Sincronizar a LUZ AUXILIAR (se habilitado)
          - if:
              - condition: template
                value_template: "{{ sync_light and light is not none and states(light) != target_state }}"
            then:
              - service: "homeassistant.turn_{{ target_state }}"
                target:
                  entity_id: "{{ light }}"

    default: []
