blueprint:
  name: Paralelo Ar Condicionado
  description: >
    Sincroniza múltiplos interruptores, um ar condicionado e uma luz auxiliar opcional.
    
    - Mudar QUALQUER interruptor (on/off) muda o estado do AC e de TODOS os outros interruptores.
    - Mudar o AC (pelo app, controle) muda o estado de TODOS os interruptores.
    - Opcionalmente, pode sincronizar uma luz auxiliar (ex: painel do AC, luz de status) com o estado do AC.
    - Opcionalmente, define modo e temperatura ao ligar.
    
    Otimizado para performance e 100% livre de loops de sincronização.
  domain: automation
  
  input:
    switch_entities:
      name: (Obrigatório) Entidades dos Interruptores
      description: Selecione UM OU MAIS interruptores (switch) que você quer sincronizar.
      selector:
        entity:
          domain: switch
          multiple: true
          
    climate_entity:
      name: (Obrigatório) Entidade do Ar Condicionado
      description: O ar condicionado (climate) que você quer sincronizar.
      selector:
        entity:
          domain: climate

    # --- Seção para Controle do Display/LEDs do AC ---
    control_display_toggle:
      name: (Opcional) Controlar Display/LEDs do AC?
      description: "Marque se deseja controlar o display/painel de LEDs do ar condicionado."
      selector:
        boolean:
      default: false
      
    display_entity:
      name: (Opcional) Entidade do Display/LEDs
      description: A entidade (light ou switch) que controla o display/painel de LEDs do ar condicionado.
      default: ""
      selector:
        entity:
          domain:
            - light
            - switch
    
    display_state:
      name: (Opcional) Estado do Display
      description: "Escolha se o display/LEDs devem ficar acesos ou apagados."
      default: "on"
      selector:
        select:
          options:
            - label: "Aceso (Ligado)"
              value: "on"
            - label: "Apagado (Desligado)"
              value: "off"
          mode: dropdown
            
    # --- Seção Opcional de Controle do AC ---
    hvac_mode_input:
      name: (Opcional) Modo do AC ao Ligar
      description: "Definir este modo HVAC (ex: 'cool', 'heat') quando o AC LIGAR. Deixe vazio para usar o último modo."
      default: ""
      selector:
        select:
          options:
            - ""
            - "cool"
            - "heat"
            - "heat_cool"
            - "auto"
            - "dry"
            - "fan_only"
          mode: dropdown
          
    target_temperature_input:
      name: (Opcional) Temperatura Alvo ao Ligar
      description: "Definir esta temperatura (em °C ou °F) quando o AC LIGAR. Deixe em 0 para não definir."
      default: 0
      selector:
        number:
          min: 0
          max: 35
          step: 0.5
          mode: box

# Define as variáveis com os inputs
variables:
  switches: !input switch_entities
  climate: !input climate_entity
  control_display: !input control_display_toggle
  display: !input display_entity
  display_desired_state: !input display_state
  hvac_mode: !input hvac_mode_input
  target_temp: !input target_temperature_input

# Otimizado para sincronização de estado
mode: restart
max_exceeded: silent

# A automação será disparada quando QUALQUER uma das entidades monitoradas mudar
trigger:
  - platform: state
    entity_id: !input switch_entities
    id: switch_trigger
  - platform: state
    entity_id: !input climate_entity
    id: climate_trigger

condition:
  # Evita loops verificando se houve mudança real de estado on/off
  - condition: template
    value_template: >
      {% if trigger.id == 'climate_trigger' %}
        {{ trigger.from_state.state != trigger.to_state.state 
           and trigger.to_state.state in ['off', 'cool', 'heat', 'heat_cool', 'auto', 'dry', 'fan_only'] }}
      {% else %}
        {{ trigger.from_state.state != trigger.to_state.state }}
      {% endif %}

action:
  - choose:
      # --- CASO 1: UM DOS INTERRUPTORES FOI O GATILHO ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'switch_trigger' }}"
        sequence:
          # Define o estado alvo
          - variables:
              target_state: "{{ trigger.to_state.state }}"

          # 1. Sincronizar OS OUTROS interruptores (somente os que estão em estado diferente)
          - service: "switch.turn_{{ target_state }}"
            target:
              entity_id: >
                {% set ns = namespace(entities=[]) %}
                {% for sw in expand(switches) %}
                  {% if sw.entity_id != trigger.entity_id and sw.state != target_state %}
                    {% set ns.entities = ns.entities + [sw.entity_id] %}
                  {% endif %}
                {% endfor %}
                {{ ns.entities }}
            continue_on_error: true

          # 2. Sincronizar o AR CONDICIONADO
          - choose:
              # --- SUB-CASO 1.1: Interruptor LIGOU e AC está OFF ---
              - conditions:
                  - condition: template
                    value_template: "{{ target_state == 'on' and is_state(climate, 'off') }}"
                sequence:
                  # Lógica de "Ligar" com opções
                  - choose:
                      # Se modo HVAC foi definido
                      - conditions:
                          - condition: template
                            value_template: "{{ hvac_mode != '' and hvac_mode is not none }}"
                        sequence:
                          - service: climate.set_hvac_mode
                            target:
                              entity_id: "{{ climate }}"
                            data:
                              hvac_mode: "{{ hvac_mode }}"
                          # Se temperatura também foi definida
                          - if:
                              - condition: template
                                value_template: "{{ target_temp > 0 }}"
                            then:
                              - delay:
                                  milliseconds: 500
                              - service: climate.set_temperature
                                target:
                                  entity_id: "{{ climate }}"
                                data:
                                  temperature: "{{ target_temp }}"
                      
                      # Se apenas temperatura foi definida
                      - conditions:
                          - condition: template
                            value_template: "{{ target_temp > 0 }}"
                        sequence:
                          - service: climate.turn_on
                            target:
                              entity_id: "{{ climate }}"
                          - delay:
                              milliseconds: 500
                          - service: climate.set_temperature
                            target:
                              entity_id: "{{ climate }}"
                            data:
                              temperature: "{{ target_temp }}"
                    
                    # Modo padrão: apenas ligar
                    default:
                      - service: climate.turn_on
                        target:
                          entity_id: "{{ climate }}"
              
              # --- SUB-CASO 1.2: Interruptor DESLIGOU e AC está ligado ---
              - conditions:
                  - condition: template
                    value_template: "{{ target_state == 'off' and not is_state(climate, 'off') }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: "{{ climate }}"
          
          # 3. Controlar o DISPLAY/LEDs do AC (se habilitado e AC ligou)
          - if:
              - condition: template
                value_template: "{{ control_display and display != '' and display is not none and target_state == 'on' }}"
            then:
              - delay:
                  milliseconds: 1000
              - service: "homeassistant.turn_{{ display_desired_state }}"
                target:
                  entity_id: "{{ display }}"
                continue_on_error: true


      # --- CASO 2: O AR CONDICIONADO FOI O GATILHO ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'climate_trigger' }}"
        sequence:
          # Define o estado alvo (AC 'off' é 'off', qualquer outra coisa é 'on')
          - variables:
              target_state: "{{ 'on' if trigger.to_state.state != 'off' else 'off' }}"

          # 1. Sincronizar TODOS os interruptores (somente os que estão em estado diferente)
          - service: "switch.turn_{{ target_state }}"
            target:
              entity_id: >
                {% set ns = namespace(entities=[]) %}
                {% for sw in expand(switches) %}
                  {% if sw.state != target_state %}
                    {% set ns.entities = ns.entities + [sw.entity_id] %}
                  {% endif %}
                {% endfor %}
                {{ ns.entities }}
            continue_on_error: true
          
          # 2. Controlar o DISPLAY/LEDs do AC (se habilitado e AC ligou)
          - if:
              - condition: template
                value_template: "{{ control_display and display != '' and display is not none and target_state == 'on' }}"
            then:
              - delay:
                  milliseconds: 1000
              - service: "homeassistant.turn_{{ display_desired_state }}"
                target:
                  entity_id: "{{ display }}"
                continue_on_error: true
