blueprint:
  name: Paralelo Virtual Otimizado (HA 2025)
  description: >
    Acende/Apaga todos os switchs/lights de um grupo simultaneamente.
    Otimizado para alta performance com múltiplos dispositivos, evitando loops.
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação/switchs
      description: Selecione todas as entidades que devem agir em conjunto.
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  # Gatilho em qualquer mudança de estado (on/off) das entidades selecionadas
  - platform: state
    entity_id: !input entrada_switchs # O !input está CORRETO aqui
    to:
      - "on"
      - "off"

action:
  # --- ESTA É A CORREÇÃO ---
  # 1. Definimos nossas variáveis primeiro.
  - variables:
      # O novo estado (on/off) que o gatilho disparou
      target_state: "{{ trigger.to_state.state }}"
      # Carregamos a lista de entidades do input para uma variável 'entities'
      entities: !input entrada_switchs
      
  # 2. Agora usamos a variável 'entities' nos templates, e não o '!input'
  - choose:
      # --- CASO 1: O gatilho foi LIGAR (on) ---
      - conditions:
          - condition: template
            value_template: "{{ target_state == 'on' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: >
                {{ expand(entities) 
                   | selectattr('state', 'eq', 'off') 
                   | map(attribute='entity_id') 
                   | list }}
                  
      # --- CASO 2: O gatilho foi DESLIGAR (off) ---
      - conditions:
          - condition: template
            value_template: "{{ target_state == 'off' }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: >
                {{ expand(entities) 
                   | selectattr('state', 'eq', 'on') 
                   | map(attribute='entity_id') 
                   | list }}

mode: restart
