blueprint:
# ... (O cabeçalho e os inputs permanecem os mesmos) ...
# ...
  input:
# ... (Inputs switch_entities, climate_entity, display, hvac_mode, target_temperature, e fan_mode_input) ...
# ...
    fan_mode_input:
      name: (Opcional) Velocidade do Vento ao Ligar
      description: "Definir a velocidade do vento (fan mode) ao ligar o AC. Deixe vazio para usar a última ou padrão."
      default: ""
      selector:
        select:
          options:
            - ""
            - "auto"
            - "low"
            - "medium"
            - "high"
          mode: dropdown

# Define as variáveis com os inputs
variables:
  switches: !input switch_entities
  climate: !input climate_entity
  control_display: !input control_display_toggle
  display: !input display_entity
  display_desired_state: !input display_state
  hvac_mode: !input hvac_mode_input
  target_temp: !input target_temperature_input
  fan_mode: !input fan_mode_input # <--- Variável do Vento

# Otimizado para sincronização de estado
mode: restart
max_exceeded: silent

# A automação será disparada quando QUALQUER uma das entidades monitoradas mudar
trigger:
  - platform: state
    entity_id: !input switch_entities
    id: switch_trigger
  - platform: state
    entity_id: !input climate_entity
    id: climate_trigger

condition:
# ... (Condição permanece a mesma) ...
  - condition: template
    value_template: >
      {% if trigger.id == 'climate_trigger' %}
        {{ trigger.from_state.state != trigger.to_state.state
            and trigger.to_state.state in ['off', 'cool', 'heat', 'heat_cool', 'auto', 'dry', 'fan_only'] }}
      {% else %}
        {{ trigger.from_state.state != trigger.to_state.state }}
      {% endif %}

action:
  - choose:
      # --- CASO 1: UM DOS INTERRUPTORES FOI O GATILHO ---
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'switch_trigger' }}"
        sequence:
          # Define o estado alvo
          - variables:
              target_state: "{{ trigger.to_state.state }}"

          # 1. Sincronizar OS OUTROS interruptores (somente os que estão em estado diferente)
          - service: "switch.turn_{{ target_state }}"
            target:
              entity_id: >
                {% set ns = namespace(entities=[]) %}
                {% for sw in expand(switches) %}
                  {% if sw.entity_id != trigger.entity_id and sw.state != target_state %}
                    {% set ns.entities = ns.entities + [sw.entity_id] %}
                  {% endif %}
                {% endfor %}
                {{ ns.entities }}
            continue_on_error: true

          # 2. Sincronizar o AR CONDICIONADO
          - choose:
              # --- SUB-CASO 1.1: Interruptor LIGOU e AC está OFF ---
              - conditions:
                  - condition: template
                    value_template: "{{ target_state == 'on' and is_state(climate, 'off') }}"
                sequence:
                  # Lógica de "Ligar" com opções (Modo, Temp, Vento)
                  - variables:
                      set_hvac: "{{ hvac_mode != '' and hvac_mode is not none }}"
                      set_temp: "{{ target_temp > 0 }}"
                      set_fan: "{{ fan_mode != '' and fan_mode is not none }}" # <--- VARIÁVEIS BOLEANAS

                  - choose:
                      # Se Modo/Temp/Vento foram definidos (Se for setar, entra aqui)
                      - conditions:
                          - condition: template
                            value_template: "{{ set_hvac or set_temp or set_fan }}" 
                        sequence:
                          # 1. Tenta ligar/setar o modo HVAC
                          - service: climate.set_hvac_mode
                            target:
                              entity_id: "{{ climate }}"
                            data:
                              hvac_mode: "{{ hvac_mode if set_hvac else state_attr(climate, 'hvac_mode') }}"
                              
                          # 2. Setar Temperatura
                          - if:
                              - condition: template
                                value_template: "{{ set_temp }}" # <--- CORREÇÃO APLICADA
                            then:
                              - delay:
                                  milliseconds: 500
                              - service: climate.set_temperature
                                target:
                                  entity_id: "{{ climate }}"
                                data:
                                  temperature: "{{ target_temp }}"
                                  
                          # 3. Setar Velocidade do Vento
                          - if:
                              - condition: template
                                value_template: "{{ set_fan }}" # <--- CORREÇÃO APLICADA
                            then:
                              - service: climate.set_fan_mode
                                target:
                                  entity_id: "{{ climate }}"
                                data:
                                  fan_mode: "{{ fan_mode }}"

                      # Caso padrão: apenas ligar (se nada foi definido)
                      default:
                        - service: climate.turn_on
                          target:
                            entity_id: "{{ climate }}"
              
              # --- SUB-CASO 1.2: Interruptor DESLIGOU e AC está ligado ---
              - conditions:
                  - condition: template
                    value_template: "{{ target_state == 'off' and not is_state(climate, 'off') }}"
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: "{{ climate }}"
          
          # 3. Controlar o DISPLAY/LEDs do AC (se habilitado e AC ligou)
          - if:
# ... (O resto do blueprint permanece o mesmo) ...
