blueprint:
  name: Paralelo Virtual
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true

trigger:
  platform: state
  entity_id: !input entrada_switchs

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id:
        !input entrada_switchs
  
  - condition: trigger  # Aplicar atraso apenas se acionado pelo grupo
    service: homeassistant.turn_off  # Serviço correto para atraso
    target:
      entity_id: '{{ trigger.entrada_switchs }}'  # Usar entidade do grupo
    delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0

mode: single
