blueprint:
  name: Alarme para Sirene Avançado
  description: >-
    Dispara uma sirene quando um sensor de porta/janela muda para um estado específico.
    Recursos disponíveis - Ativação/desativação do som - Nível de volume configurável - Melodia/tom personalizável - Duração do alarme (0 para indefinido) - Modo de repetição - Notificação opcional - Tempo de espera antes de reativar
  domain: automation

  input:
    # ========== GATILHO ==========
    trigger_sensor:
      name: Sensor de Gatilho
      description: O sensor que irá disparar o alarme (porta, janela, movimento, etc)
      selector:
        entity:
          domain: 
            - binary_sensor
            - sensor

    trigger_state:
      name: Estado para Disparar
      description: O estado do sensor que deve acionar o alarme
      default: "on"
      selector:
        select:
          options:
            - label: "Aberto / Detectando (on)"
              value: "on"
            - label: "Fechado / Limpo (off)"
              value: "off"

    # ========== DISPOSITIVO ==========
    alarm_switch:
      name: Switch do Alarme
      description: Selecione a entidade switch.xxx_alarm da sirene
      selector:
        entity:
          domain: switch

    alarm_melody:
      name: Melodia do Alarme
      description: Selecione a entidade select.xxx_melody da sirene
      selector:
        entity:
          domain: select

    alarm_volume:
      name: Volume do Alarme
      description: Selecione a entidade select.xxx_volume da sirene
      selector:
        entity:
          domain: select

    alarm_duration:
      name: Duração do Alarme (entidade)
      description: Selecione a entidade number.xxx_duration da sirene
      selector:
        entity:
          domain: number

    # ========== CONFIGURAÇÕES DE SOM ==========
    enable_sound:
      name: Ativar Som
      description: Se marcado, o alarme emitirá som
      default: true
      selector:
        boolean:

    volume_level:
      name: Nível de Volume
      description: Volume do alarme (Low, Medium ou High)
      default: "high"
      selector:
        select:
          options:
            - label: "Baixo (Low)"
              value: "low"
            - label: "Médio (Medium)"
              value: "medium"
            - label: "Alto (High)"
              value: "high"

    melody_number:
      name: Melodia
      description: Escolha a melodia de 1 a 18
      default: 5
      selector:
        number:
          min: 1
          max: 18
          step: 1
          mode: slider

    duration_seconds:
      name: Duração do Alarme
      description: Tempo que o alarme tocará em segundos (0 = indefinido, até parar manualmente)
      default: 60
      selector:
        number:
          min: 0
          max: 1800
          step: 1
          unit_of_measurement: "segundos"
          mode: box

    # ========== OPÇÕES AVANÇADAS ==========
    repeat_alarm:
      name: Repetir Alarme
      description: Repetir o alarme múltiplas vezes (útil para durações curtas)
      default: 1
      selector:
        number:
          min: 1
          max: 10
          step: 1
          mode: box

    delay_between_repeats:
      name: Pausa entre Repetições
      description: Tempo de espera entre cada repetição do alarme
      default: 2
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: "segundos"
          mode: box

    cooldown_period:
      name: Período de Espera entre Acionamentos
      description: Tempo mínimo entre acionamentos externos do alarme (evita disparos múltiplos do mesmo sensor). Não afeta repetições.
      default: 30
      selector:
        number:
          min: 0
          max: 300
          step: 5
          unit_of_measurement: "segundos"
          mode: box

    # ========== NOTIFICAÇÕES ==========
    send_notification:
      name: Enviar Notificação
      description: Enviar notificação quando o alarme disparar
      default: false
      selector:
        boolean:

    notification_service:
      name: Serviço de Notificação
      description: Digite o serviço de notificação (exemplo - notify.mobile_app_seu_telefone)
      default: "notify.notify"
      selector:
        text:

    notification_title:
      name: Título da Notificação
      description: Título da mensagem de notificação
      default: "Alarme Disparado"
      selector:
        text:

    notification_message:
      name: Mensagem da Notificação
      description: Corpo da notificação. Use trigger_name para incluir o nome do sensor
      default: "O sensor trigger_name foi ativado"
      selector:
        text:
          multiline: true

# ========== VARIÁVEIS ==========
variables:
  sensor_entity: !input trigger_sensor
  switch_entity: !input alarm_switch
  melody_entity: !input alarm_melody
  volume_entity: !input alarm_volume
  duration_entity: !input alarm_duration
  sound_enabled: !input enable_sound
  volume: !input volume_level
  melody: !input melody_number
  duration: !input duration_seconds
  repeats: !input repeat_alarm
  repeat_delay: !input delay_between_repeats
  cooldown: !input cooldown_period
  notify_enabled: !input send_notification
  notify_service: !input notification_service
  notify_title: !input notification_title
  notify_message: !input notification_message
  trigger_name: "{{ state_attr(sensor_entity, 'friendly_name') | default(sensor_entity) }}"

# ========== GATILHO ==========
trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: !input trigger_state
    for:
      seconds: 2

# ========== CONDIÇÕES ==========
condition:
  # Verifica cooldown apenas entre acionamentos diferentes (não afeta repetições internas)
  - condition: template
    value_template: >-
      {% set last_triggered = state_attr(this.entity_id, 'last_triggered') %}
      {% if last_triggered == none %}
        true
      {% else %}
        {{ (now() - last_triggered).total_seconds() > cooldown }}
      {% endif %}

# ========== AÇÃO ==========
action:
  # 1. Envia notificação (se habilitada)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notify_enabled }}"
        sequence:
          - service: "{{ notify_service }}"
            data:
              title: "{{ notify_title }}"
              message: "{{ notify_message.replace('trigger_name', trigger_name) }}"

  # 2. Ativa o alarme (se o som estiver habilitado)
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ sound_enabled }}"
        sequence:
          # Configura melodia e volume uma vez antes do loop
          - service: select.select_option
            target:
              entity_id: "{{ melody_entity }}"
            data:
              option: "{{ melody | string }}"

          - service: select.select_option
            target:
              entity_id: "{{ volume_entity }}"
            data:
              option: "{{ volume }}"

          # Configura duração (se > 0)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ duration > 0 }}"
                sequence:
                  - service: number.set_value
                    target:
                      entity_id: "{{ duration_entity }}"
                    data:
                      value: "{{ duration }}"

          # Loop de repetições
          - repeat:
              count: "{{ repeats }}"
              sequence:
                # Liga o alarme
                - service: switch.turn_on
                  target:
                    entity_id: "{{ switch_entity }}"

                # Aguarda a duração + pausa (se não for a última repetição)
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ repeat.index < repeats }}"
                      sequence:
                        - delay:
                            seconds: "{{ duration + repeat_delay if duration > 0 else repeat_delay }}"
                        
                        # Desliga o alarme antes da próxima repetição
                        - service: switch.turn_off
                          target:
                            entity_id: "{{ switch_entity }}"
                        
                        - delay:
                            seconds: "{{ repeat_delay }}"

mode: single
max_exceeded: silent
